### ISSUE TITLE
TODO Megathread

### ISSUE THREAD

**Issue by quinnouyang** [staylor7/rare#10]
## Sunburst Diagram #9 
- Stratify JSON (@SallyXue-0114) [DONE]
- - Choose between hierarchies:
- - - `category` -> `chakra` -> `disease` -> `...` (rest of details as leaves)
- - - `category` -> `chakra` -> `phenotype` -> `disease` -> `...` (rest of details as leaves)
- - Consider combining `category` and `chakra` at the JSON level (not the CSV)

## Viola Playback (@quinnouyang)
- Standard playback with slider
- Timestamps to diseases (@staylor7) for playback [DONE, just add as CSV column]
- - As playback progresses, disease UI "fires" according to playback
- - Clicking a disease jumps to timestamp in piece (?)
- Discuss and finalize UI behavior during viola playback (compared to chakra playback)

## Chakra Playback (@SallyXue-0114)
- Clicking on chakra/category playbacks according to its looped ambient sound (see https://github.com/staylor7/rare-diseases/tree/main/public/chakra_sounds_mp3) [DONE]
- Clicking on a disease playbacks over its chakra's sound [DONE]
- Remove hover playback [DONE]
- #14 [NOT STARTED]

## Miscellaneous
- Splash intro/help screen (also consequently solves #8)
- Kill audio button for development
- CI/CD #13

**Comment by SallyXue-0114** [comment]
Hi @staylor7 @quinnouyang ! About my new updates in 'sunburst-js' branch: 
1. I created a chart with a hierarchy structured as 'category (chakra) - Disease - everything else'.
2. For texts that are too long (e.g., Malacards), I label them as 'hover for details', enabling you to see the full text when you hover over it (our original feature). See the demo for more details.
https://github.com/staylor7/rare-diseases/assets/92959551/b930dbba-3e08-4e1f-910b-f7c8591c4e17

To run the code, simply clone 'sunburst-js' to your device and run the code in your web server!
I believe the next step will be to merge this current JavaScript with our TypeScript version? I'm also willing to help with the playback features once the merging is complete. :)

**Comment by quinnouyang** [comment]
Closing as we have dedicted issues for all of the relevant ones here
