### ISSUE TITLE
Viola playback

### ISSUE THREAD

**Issue by quinnouyang** [staylor7/rare#17]
- Standard playback with slider
- Timestamps to diseases (@staylor7) for playback [DONE, just add as CSV column]
- As playback progresses, disease UI "fires" according to playback
- Clicking a disease jumps to timestamp in piece (?)
- Discuss and finalize UI behavior during viola playback (compared to chakra playback)

**Comment by SallyXue-0114** [comment]
pause viola/sunburst sound when the other one is playing
