### ISSUE TITLE
Set metadata (favicon, preview, etc.)

### ISSUE THREAD

**Issue by quinnouyang** [staylor7/rare#19]
Trivial things, basically replace the Vite defaults. Also room to improve README etc.

**Comment by quinnouyang** [comment]
@staylor7 Do you have a brief idea of what to make our favicon as? Currently it's the default logo
![image](https://github.com/staylor7/rare-diseases/assets/90884224/dc2f4daa-ccb7-4c0e-95e2-b235a7e09f96)

Might be able to get away with a basic version of the sunburst

**Comment by staylor7** [comment]
The sunburst would be cool!
