### ISSUE TITLE
Hover over the individual disease for both playback and information

### ISSUE THREAD

**Issue by SallyXue-0114** [staylor7/rare#21]
don't need the detail layer circle.
when hover over, pop up window (small) that display detailed informations (that are originally in the detail layer circle) + blurred out the disease circle. 
Also update the hierarchy.json using the new csv

**Comment by SallyXue-0114** [comment]
https://github.com/staylor7/rare-diseases/assets/92959551/019f1691-fc6e-43e5-8abf-57a23b161134

a demo (the 'Link' is actually clickable, I forgot to show)
I have also tried mouseover (hover over) but somehow it didn't work...so I use click for both information and audio for now, felt like it's not a bad design decision though?

**Comment by quinnouyang** [comment]
yaay! if you need help with mouseover for audio, open a PR and I can try
