### ISSUE TITLE
Design: colors, font, etc.

### ISSUE THREAD

**Issue by quinnouyang** [staylor7/rare#24]
## Colors
- Waiting on chakra/category colors from @staylor7 
- Do we want different colors (shadings?) for diseases?

## Font
- Currently on `10px sans-serif`

**Comment by quinnouyang** [comment]
At the disease level, should the arc lengths be proportional to the length of the promoter sequence (and consequantly the duration of their sound)? Can set a minimum length too

**Comment by quinnouyang** [comment]
Just noticed that chakras and categories are not one-to-one: e.g. the rishi chakra applies to 4 (?) categories, each with a different arc and audio context (though audio sources are the same). This is fine? @staylor7

**Comment by staylor7** [comment]
Oh yes! Some chakras do include multiple categories - from what I understand those categories are closely related, so Aditi included them in the same chakra. Is that what you mean?

**Comment by quinnouyang** [comment]
Yep! I think we currently ignore reclicks of the same chakra—do we want to tweak that to same categories/arc?

**Comment by staylor7** [comment]
Yes, let’s make that the same for categories, arcs, thanks!On Mar 14, 2024, at 12:04 PM, Quinn Ouyang ***@***.***> wrote:﻿
Yep! I think we currently ignore reclicks of the same chakra—do we want to tweak that to same categories/arc?

**Comment by staylor7** [comment]
It looks and sounds fantastic! I do have one question. When we click on a disease, its info is displayed in a box, but we can’t see anything behind the info box.

Is it possible to make the info box translucent, so we can click on items behind the info box?

**Comment by staylor7** [comment]
Here are the right colors - I may have put these in the wrong thread, sorry....

ritu #bebada
indu #fcaea4
vasu	#81b2d2
rudra #fcbc73
veda #b3dd69
aditya #fdd8eb
dishi #d9d9d9
bana #bc80bd
bhrama #d5eecf
netra #ffed6f
agni #93d6ca
rishi #ffd9b3

**Comment by SallyXue-0114** [comment]
> It looks and sounds fantastic! I do have one question. When we click on a disease, its info is displayed in a box, but we can’t see anything behind the info box.
> 
> Is it possible to make the info box translucent, so we can click on items behind the info box?

Yes making the box translucent is easy, something like this:
<img width="1428" alt="截屏2024-03-16 下午12 56 45" src="https://github.com/staylor7/rare-diseases/assets/92959551/35aed8d2-7979-4cb3-9c0d-53f4d0856313">

However, it could be hard to directly click the things behind the window while the window is open (quinn maybe you have a better way?), but users can definitely scroll up and down a bit to click, given that now they can see what is behind the window.

**Comment by SallyXue-0114** [comment]
<img width="1032" alt="截屏2024-03-16 下午1 32 29" src="https://github.com/staylor7/rare-diseases/assets/92959551/1a61ac5b-3cad-4222-9bb9-ede51b3e91ad">
New colors 🎉

**Comment by quinnouyang** [comment]
@SallyXue-0114 Issue might be moot if we make the popup width smaller (more square-like is better as it would align with the rotational symmetry of the sunburst). Most of that space is taken by the promoter sequence; we can also inline the link into a `See more information` etc.

Can hard-code this somewhat for now (maybe a % of sunburst width?) but ideally we employ some responsive sizing that works alongside the sunburst.

**Comment by quinnouyang** [comment]
@SallyXue-0114 @staylor7 Also quick design suggestions:
- Wider margins
- Distinct title of disease from rest of card
- Move description to right below title (and with the right formatting, can omit `Description: `). In general, order of information can change to fit what makes sense to read vs. on the CSV. 
- Overall, imagine a general user's POV reading this card to present this information in the most understandable way possible, which is not necessarily like in the CSV.

Maybe Aditi has some thoughts?

**Comment by staylor7** [comment]
This all sounds great, thanks Quinn!

**Comment by SallyXue-0114** [comment]
<img width="1512" alt="截屏2024-03-16 下午7 33 59" src="https://github.com/staylor7/rare-diseases/assets/92959551/6fe85335-533c-4520-82c5-e0961ec0aff6">
Here's a new version of design!
A thing is I tried multiple ways, but can't seem to place the 'Promoter' and 'Link' label and their actual content in the same line...Which version do you guys think would be better?

**Comment by staylor7** [comment]
Gorgeous!! Yay!

**Comment by quinnouyang** [comment]
I don't mind the newlines, though we can also inline the link into the title or as a `Learn more`, etc.

While information display is fine, I don't think it makes much sense to the average person. There's a balance/comrpomise between abstracting away scientific details and user intuition–we're fine right now but curious if we can do better somehow? Not neccessary ofc

**Comment by quinnouyang** [comment]
BTW, do we still want the opaque window even though it now usually doesn't cover much of the diagram? (Would probably break on small/large screens but to fix later...)

**Comment by quinnouyang** [comment]
@staylor7 Do we want to keep the purple header color? I was thinking to base it off the new chakra ones or make it black.

**Comment by staylor7** [comment]
One of the chakra colors would be nice!
