### ISSUE TITLE
Missing vasu chakra sound

### ISSUE THREAD

**Issue by quinnouyang** [staylor7/rare#29]
There's only 11 in `assets/chakra` D:

**Comment by quinnouyang** [comment]
@staylor7 Can you upload this into `assets/chakra`?

**Comment by staylor7** [comment]
I *think* that the vasu category is so small that I decided not to make a background sound - so for that one, we should just keep playing whatever sound is already playing. I hope that’s OK!

**Comment by quinnouyang** [comment]
Gotcha, we'll make the exception

**Comment by quinnouyang** [comment]
Though what happens when the first chakra the user clicks is `vasu`...is silence OK?

**Comment by staylor7** [comment]
Good question! Since Vasu is very tiny I think it’s OK. On Mar 16, 2024, at 12:41 AM, Quinn Ouyang ***@***.***> wrote:﻿
Though what happens when the first chakra the user clicks is vasu...is silence OK?

**Comment by quinnouyang** [comment]
Cool, fix is pending on commit https://github.com/staylor7/rare-diseases/pull/32/commits/3b110c26a4a5aa5550ce55b2b8c1e5632910efa8

**Comment by SallyXue-0114** [comment]
@staylor7 Hi Professor! We find out that vasu is not only missing the chakra sound, but also most of the informations in the csv file:
<img width="1059" alt="截屏2024-03-16 下午8 16 49" src="https://github.com/staylor7/rare-diseases/assets/92959551/96c26772-c81c-4862-9a42-9e6b817c3f0c">

Should we just exclude vasu in this case?

**Comment by staylor7** [comment]
I think it might be a category without any diseases in it! Yes, let’s leave it out if that’s easier.
