### ISSUE TITLE
[STAGING] Viola audio has incorrect path and AudioContext can fail to initialize

### ISSUE THREAD

**Issue by quinnouyang** [staylor7/rare#30]
## Issue

See [staging site](https://stephenandrewtaylor.net/rare-test/):
- `Failed to load resource: net::ERR_BLOCKED_BY_CLIENT`
- `Failed to load resource: the server responded with a status of 404`
- `The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu`
- `git bisect` shows problematic commit: https://github.com/staylor7/rare-diseases/commit/96adaae1b2561369265492624e0b786d84ad27c2

## To reproduce
- `git checkout 96adaae`
- In `vite.config.js`, replace `https://stephenandrewtaylor.net/rare-test` with `http://localhost:4173/rare-test`.
- `npm run build && npm run preview`
- See console and note failed playback

**Comment by staylor7** [comment]
Do you mean the playbar at the top? That’s weird, I’m not sure why that’s happening. But the Web Audio API does require user interaction before any sound plays. Maybe we can have text at the top that gives a short intro?On Mar 14, 2024, at 8:11 PM, Quinn Ouyang ***@***.***> wrote:﻿
See staging site:

Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
Failed to load resource: the server responded with a status of 404
The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu

git bisect shows problematic commit: 96adaae

**Comment by quinnouyang** [comment]
Not just the playback controls, but the diagram itself. Clicking play would be a user interaction so should be valid, but perhaps we can't init an AudioContext without that first. The failed resources might be a separate issue though

**Comment by quinnouyang** [comment]
Slightly more fixed now but I sometimes run into some serious delay and loading issues for the sounds. Cannot replicate locally, only on staging environment.
