### ISSUE TITLE
[STAGING] Unsecured HTTP warning from no 3rd-party SSL/TLS certificates

### ISSUE THREAD

**Issue by quinnouyang** [staylor7/rare#34]
Gonna try (temporarily?) moving DNS management to personal Cloudflare

**Comment by quinnouyang** [comment]
Pending nameserver changes...

**Comment by staylor7** [comment]
Anything you need me to do? Should we use an Illinois.edu server?

**Comment by quinnouyang** [comment]
I'll find out–I think I can just (temporarily) switch to use Cloudflare's CDN under my account and that also enables me to add free certificates without leaving GoDaddy as a domain owner (and hosting provider).

**Comment by quinnouyang** [comment]
Looks good for now! @staylor7 we can talk about whether you want this as a permanent solution, i.e. move _domain ownership_ to Cloudflare (while still hosting on GoDaddy) so you get free SSL/TLS certificates (and a cheaper renewal plan?).
