### ISSUE TITLE
potential typos in seq.d3-2024.csv

### ISSUE THREAD

**Issue by SallyXue-0114** [staylor7/rare#39]
@staylor7 Hi Professor! I see some potential typos in the seq.d3-2024.csv that I'm not sure if they are typos or not:
1. 
<img width="769" alt="截屏2024-03-17 下午6 45 19" src="https://github.com/staylor7/rare-diseases/assets/92959551/dee85b7e-719e-453b-8ef6-64bfca093d5e">
There's a category name 'circulatory' and another name 'cirulatory'. Should they all be 'circulatory'?

2. 
<img width="729" alt="截屏2024-03-17 下午6 47 04" src="https://github.com/staylor7/rare-diseases/assets/92959551/579d4f1a-cc2d-41a3-8864-f56f56421397">
Should the 'msk' all be lowercase?

**Comment by staylor7** [comment]
Yes- you are right about both of those, thanks!On Mar 17, 2024, at 6:51 PM, SallyXue-0114 ***@***.***> wrote:﻿
@staylor7 Hi Professor! I see some potential typos in the seq.d3-2024.csv that I'm not sure if they are typos or not:
1.
2024-03-17.6.45.19.png (view on web)
There's a category name 'circulatory' and another name 'cirulatory'. Should they all be 'circulatory'?



2024-03-17.6.47.04.png (view on web)
Should the 'msk' all be lowercase?
