### ISSUE TITLE
UI and csv issues

### ISSUE THREAD

**Issue by staylor7** [staylor7/rare#44]
Congrats on last week's successful conference presentation! I'm finally getting back to this and I've found a few things, at least when I'm running it on Chrome:

- can the Ritu category be at 12 o'clock? 
- looping of background sounds doesn't seem to work.
- the order of the chakras around the circle should follow the order in the csv, clockwise; but instead they seem to go counterclockwise from 12:00 in order of smallest to largest.
- When we deleted the Vasu chakra because it has no diseases, that threw off the timing of the viola piece by one line, starting at line 34 in the csv. The interactive version also gets thrown off there, so every disease's sound file is off by one. Is it OK to add back that Vasu chakra line, at line 34 in the csv, even though it doesn't do anything? Is that going to mess up the d3 code?
- I'll come up with some more explanatory text - thanks again you two!

**Comment by quinnouyang** [comment]
1. I believe positioning only depends on the order of diseases in the CSV, so this should be trivial
2. Right, chakra looping is missing (I probably broke something)
3. Also dependant on CSV order, though possibly we may want to correct this in the JSON OR drawing stage.
4. We can add back Vasu and handle a missing audio event as not an error
5. Yep!

**Comment by SallyXue-0114** [comment]
Sure, will take a closer look after next weekend! pretty busy with exams these 2 weeks 😭

**Comment by quinnouyang** [comment]
yah ofc no rush:) ill have some scattered hours to work on this after these 2ish weeks too

**Comment by SallyXue-0114** [comment]
<img width="941" alt="solve UI" src="https://github.com/staylor7/rare-diseases/assets/92959551/0dba4fcc-9e01-4554-8853-ebf49fb00e45">
Seems like I solved problem 1 and 3! Should I just push them to main or should I open a new branch? @quinnouyang @staylor7

**Comment by staylor7** [comment]
Thanks Sally! Yeah, go ahead and push them to main!

Steve
_________________________________
Stephen Taylor
Professor of Composition-Theory
School of Music, University of Illinois at Urbana-Champaign
co-director, Illinois Modern Ensemble
www.stephenandrewtaylor.net
217 333-3712 office
