### ISSUE TITLE
Automatic CI/CD via CPanel GitHub integration

### ISSUE THREAD

**Issue by quinnouyang** [staylor7/rare#6]
TODO, off the top of my head:
- Development vs. production configurations (base URL, etc.). Not the same as `dev` vs. `build`?
- Instructions for manual deployment for @staylor7 
- Automated deployment using CPanel GitHub integration, though I forget if it's truly hands-off once setup correctly. **Will require protecting `main` branch.**

**Comment by staylor7** [comment]
Yay, thanks Quinn! I am ashamed to say I can’t remember how to do the build thing in Terminal. I just need to go and dig up your old email!

Steve

**Comment by quinnouyang** [comment]
Of course! Off the top of my head: `npm run build` and upload that folder like it is in the `public_html` (keep the `.htaccess` and any other files missing from this build)
